# Generated by Django 5.1 on 2024-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_mobile_phone",
                    models.CharField(max_length=11, verbose_name="管理员电话"),
                ),
                (
                    "admin_account",
                    models.CharField(max_length=20, verbose_name="管理员账号"),
                ),
                (
                    "admin_password",
                    models.CharField(max_length=20, verbose_name="管理员密码"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="文档名称")),
                ("type", models.CharField(max_length=10, verbose_name="文档类型")),
                (
                    "modify_permission",
                    models.CharField(max_length=1, verbose_name="文档修改权限"),
                ),
                ("create_time", models.DateTimeField(verbose_name="文档创建时间")),
                ("update_time", models.DateTimeField(verbose_name="文档更新时间")),
                ("path", models.CharField(max_length=50, verbose_name="文档路径")),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kb_name", models.CharField(max_length=50)),
                ("kb_state", models.CharField(max_length=1)),
                ("kb_content", models.DateField()),
                ("create_Time", models.DateField()),
                ("update_Time", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "knowledge_base",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="用户名")),
                ("account", models.CharField(max_length=20, verbose_name="账号")),
                ("password", models.CharField(max_length=20, verbose_name="密码")),
                ("isadmin", models.CharField(max_length=1, verbose_name="是否为管理员")),
                ("phone", models.CharField(max_length=11, verbose_name="电话")),
                ("create_time", models.DateTimeField(verbose_name="创建时间")),
                ("update_time", models.DateTimeField(verbose_name="更新时间")),
            ],
        ),
    ]
