# Generated by Django 5.1 on 2024-09-05 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataBase", "0005_remove_user_username_user_account_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="knowledgebase",
            old_name="kb_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="kb_content",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="kb_description",
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="description",
            field=models.CharField(
                blank=True, default="为您的知识库创建描述", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dialog",
            name="attach_knowledgebase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="DataBase.knowledgebase",
                verbose_name="关联知识库",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=11, verbose_name="手机号"),
        ),
    ]
