# Generated by Django 5.1 on 2024-08-30 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataBase", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="knowledgebase",
            table=None,
        ),
    ]
