# Generated by Django 5.1 on 2024-09-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataBase", "0002_alter_knowledgebase_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="modify_permission",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="kb_state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="isadmin",
        ),
        migrations.AddField(
            model_name="document",
            name="attach_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataBase.user",
                verbose_name="文档创建者",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="attach_document",
            field=models.ManyToManyField(
                blank=True, null=True, to="DataBase.document", verbose_name="知识库文档"
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="kb_description",
            field=models.CharField(default="为您的知识库创建描述", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.CharField(default="0", max_length=1, verbose_name="是否为管理员"),
        ),
        migrations.AlterField(
            model_name="document",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="文档创建时间"),
        ),
        migrations.AlterField(
            model_name="document",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="文档更新时间"),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="create_Time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="kb_content",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="update_Time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="user",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, null=True, verbose_name="对话标题"),
                ),
                (
                    "state",
                    models.CharField(default="0", max_length=1, verbose_name="对话状态"),
                ),
                ("content", models.JSONField(null=True, verbose_name="对话内容")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="对话创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="对话更新时间"),
                ),
                (
                    "attach_knowledgebase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataBase.knowledgebase",
                        verbose_name="关联知识库",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataBase.user",
                        verbose_name="对话创建者",
                    ),
                ),
            ],
        ),
    ]
