# Generated by Django 5.1 on 2024-09-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataBase", "0003_remove_document_modify_permission_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="用户名"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="attach_document",
            field=models.ManyToManyField(
                blank=True, to="DataBase.document", verbose_name="知识库文档"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=11, unique=True, verbose_name="手机号"),
        ),
    ]
