# Generated by Django 5.1 on 2024-09-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataBase", "0004_remove_user_account_remove_user_is_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="account",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="账号"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="姓名"
            ),
        ),
    ]
