# Generated by Django 5.1 on 2024-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataBase", "0006_rename_kb_name_knowledgebase_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="姓名"
            ),
        ),
    ]
