# Generated by Django 5.1 on 2024-09-05 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataBase", "0008_knowledgebase_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="attach_document",
        ),
        migrations.AddField(
            model_name="document",
            name="attach_knowledge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataBase.knowledgebase",
                verbose_name="文档所属知识库",
            ),
        ),
        migrations.AlterField(
            model_name="dialog",
            name="content",
            field=models.JSONField(blank=True, null=True, verbose_name="对话内容"),
        ),
        migrations.AlterField(
            model_name="dialog",
            name="state",
            field=models.CharField(
                blank=True, default="0", max_length=1, null=True, verbose_name="对话状态"
            ),
        ),
    ]
