# Generated by Django 5.1 on 2024-09-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataBase", "0009_remove_knowledgebase_attach_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="path",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="upload/", verbose_name="文档路径"
            ),
        ),
    ]
